[package]
name = "acro_build"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.12"
flate2 = "1.0.34"
human_bytes = "0.4.3"
tar = "0.4.43"
tracing = "0.1.40"
ureq = "2.10.1"
walkdir = "2.5.0"
zip = { version = "2.2.2", default-features = false }
