[package]
name = "acro_math"
version = "0.1.0"
edition = "2021"

[dependencies]
acro_ecs = { path = "../acro_ecs" }
acro_reflect = { path = "../acro_reflect" }
acro_scripting = { path = "../acro_scripting" }
cfg-if = "1.0.0"
nalgebra = "0.33.0"
tracing = "0.1.40"

[features]
double-precision = []
