[package]
name = "acro_reflect"
version = "0.1.0"
edition = "2021"

[dependencies]
acro_ecs = { path = "../acro_ecs" }
reflect_derive = { path = "./reflect_derive" }
eyre = "0.6.12"
nalgebra = "0.33.0"
serde = { version = "1.0.204", features = ["derive"] }
